version: "2"
services:
    web:
        build:
            context: .
        ports:
            - "81:80"
        volumes:
          - ./certs:/home/pki/srv
        environment:
          - PUBFQDN=
        hostname: $PUBFQDN
        restart: always
    registry:
        image:
          registry:2
        ports:
            - "443:443"
        environment:
            - REGISTRY_HTTP_ADDR=0.0.0.0:443
            - REGISTRY_HTTP_TLS_CERTIFICATE=certs/repo.crt
            - REGISTRY_HTTP_TLS_KEY=certs/repo.key
        volumes:
          - ./certs:/certs
        restart: always
